services:
  - type: web
    name: football501
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run server
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
