// ─────────────────────────────────────────────────────────────────────────
// CENTRAL SEO CONFIG — single source of truth for every route.
//
// Used by BOTH the client (<Seo> head manager, for SPA navigation) and the
// build-time prerender (scripts/prerender.mjs, which writes a unique static
// HTML file per route + sitemap.xml + robots.txt). Plain JS so Node and the
// browser can both import it. Change the domain in ONE place (SITE_URL).
// ─────────────────────────────────────────────────────────────────────────

export const SITE_URL = 'https://footballtriviagames.onrender.com'
export const BRAND = 'Football Trivia Games'
export const TWITTER = '@footballtrivia'
// 1200×630 social-share image (generated by scripts/og-images.mjs). Per-route
// images are set via route.ogImage; this is the fallback.
export const DEFAULT_OG_IMAGE = `${SITE_URL}/og/default.png`

export const absolute = (path) => (path === '/' ? SITE_URL + '/' : SITE_URL + path)

// One entry per route. Titles ≤ ~60 chars, descriptions ~150–160 chars,
// keyword-rich and unique (duplicate titles/descriptions are a ranking killer).
export const ROUTES = [
  {
    path: '/',
    name: 'Home',
    title: 'Football Trivia Games — Free Daily Football Quiz Games',
    description: 'Free daily football trivia games: Football Wordle, a footy Tic-Tac-Toe grid, name the top 10, and guess the player from their teammates. Play solo or 1v1.',
    keywords: ['football trivia games', 'football quiz', 'soccer trivia', 'daily football game', 'football guessing game'],
    h1: 'Football Trivia Games',
    tagline: 'A growing collection of free daily football trivia games. No sign-up, just play.',
    about: 'Football Trivia Games brings together the best free daily football quiz games in one place. Test your knowledge with Football Wordle, fill a Football Tic-Tac-Toe grid, race against the clock in Football Tenable, or guess the mystery player from their teammates — all playable instantly in your browser on mobile or desktop.',
    howTo: [],
    faq: [
      { q: 'What is Football Trivia Games?', a: 'Football Trivia Games is a free collection of daily football quiz games — including Football Wordle, Football Tic-Tac-Toe, Football Tenable and Guess the Player — playable in your browser with no sign-up.' },
      { q: 'Are the games free to play?', a: 'Yes. Every game is completely free, runs in your browser, and needs no account or download.' },
      { q: 'Do new puzzles appear every day?', a: 'Yes. The daily games refresh at local midnight, and the guessing and 1v1 modes can be replayed as often as you like.' },
    ],
    schema: 'WebSite',
    priority: '1.0',
    changefreq: 'daily',
  },
  {
    path: '/wordle',
    name: 'Football Wordle',
    title: 'Football Wordle — Guess the Footballer | Football Trivia Games',
    description: "Play Football Wordle: guess the mystery footballer's surname in six tries. A new player every day — green is the right spot, yellow the right letter, wrong spot.",
    keywords: ['football wordle', 'soccer wordle', 'guess the footballer', 'footballer wordle', 'football word game'],
    h1: 'Football Wordle',
    tagline: "Guess the mystery footballer's surname in six tries.",
    ogImage: '/og/wordle.png',
    about: 'Football Wordle is a daily football word game in the style of Wordle. Each day a famous footballer is chosen and you have six guesses to work out their surname, using green and yellow letter clues to narrow it down. It is a quick, addictive test for any football fan.',
    howTo: [
      'A new famous footballer is chosen every day.',
      'Type a real surname and submit your guess.',
      'Green means the letter is in the right spot; yellow means right letter, wrong spot; grey means it is not in the surname.',
      'Solve the surname within six guesses to win.',
    ],
    faq: [
      { q: 'What is Football Wordle?', a: "Football Wordle is a daily word game where you guess a famous footballer's surname in six tries, using green and yellow colour clues just like Wordle." },
      { q: 'How many guesses do I get?', a: 'You get six guesses to find the footballer’s surname.' },
      { q: 'Does the footballer change every day?', a: 'Yes — a new footballer is selected each day and refreshes at local midnight.' },
    ],
    schema: 'VideoGame',
    priority: '0.9',
    changefreq: 'daily',
  },
  {
    path: '/tictactoe',
    name: 'Football Tic-Tac-Toe',
    title: 'Football Tic-Tac-Toe — Daily Grid & 1v1 | Football Trivia Games',
    description: 'Play Football Tic-Tac-Toe: a 3x3 grid where every row and column is a football category. Name a player who fits both to claim a square. Daily solo grid or local 1v1.',
    keywords: ['football tic tac toe', 'footy grid', 'football grid game', 'soccer tic tac toe', 'football category grid'],
    h1: 'Football Tic-Tac-Toe',
    tagline: 'Two football categories meet in every square — name a player who fits both.',
    ogImage: '/og/tictactoe.png',
    about: 'Football Tic-Tac-Toe, also known as a footy grid, challenges your knowledge of clubs, leagues, nationalities and trophies. Claim a square by naming a footballer who matches both its row and column category — then play the daily grid solo or go head-to-head with a friend in local 1v1 mode.',
    howTo: [
      'Every row and column is a football category — a club, league, nationality or trophy.',
      'Pick a square and name a player who satisfies BOTH its row and column category.',
      'No player can be used twice on the same grid.',
      'In the daily mode, fill all nine squares before your lives run out. In 1v1, take turns and get three in a row to win.',
    ],
    faq: [
      { q: 'How does Football Tic-Tac-Toe work?', a: 'Each row and column of the 3x3 grid is a football category. To claim a square you name a player who fits both the row and the column — for example a player who played for a given club AND won a given trophy.' },
      { q: 'Can I play Football Tic-Tac-Toe with a friend?', a: 'Yes. The 1v1 mode lets two players share one device, taking turns to claim squares. The first to three in a row wins.' },
      { q: 'Does the daily grid change every day?', a: 'Yes — the daily challenge generates a fresh, solvable grid each day.' },
    ],
    schema: 'VideoGame',
    priority: '0.9',
    changefreq: 'daily',
  },
  {
    path: '/teammates',
    name: 'Guess the Player',
    title: 'Guess the Footballer from Teammates | Football Trivia Games',
    description: 'Guess the mystery footballer from their real teammates, revealed one at a time. Work out who it is in five guesses in this addictive football guessing game.',
    keywords: ['guess the footballer', 'guess the football player', 'football guessing game', 'name the footballer', 'teammates football game'],
    h1: 'Guess the Player',
    tagline: 'Identify the mystery footballer from the players they actually played with.',
    ogImage: '/og/teammates.png',
    about: 'Guess the Player is a football guessing game where you identify a mystery footballer from the real players they lined up alongside. A new teammate is revealed after every wrong guess, so the more football you know, the faster you will crack it.',
    howTo: [
      'A well-known footballer is chosen at random.',
      'One of their real former teammates is revealed.',
      'Guess who the mystery player is. A wrong guess reveals another teammate.',
      'Work it out within five guesses to win.',
    ],
    faq: [
      { q: 'How do I play Guess the Player?', a: 'You are shown one real teammate of a mystery footballer. Guess who the mystery player is; each wrong guess reveals another teammate, up to five clues.' },
      { q: 'How many guesses do I get?', a: 'You get five guesses, with a new teammate revealed after each wrong answer.' },
      { q: 'Are the teammates accurate?', a: 'Yes — teammates are players who genuinely shared a club or national team during overlapping years.' },
    ],
    schema: 'VideoGame',
    priority: '0.9',
    changefreq: 'weekly',
  },
  {
    path: '/career-path',
    name: 'Career Path',
    title: 'Career Path — Guess the Footballer | Football Trivia Games',
    description: 'Guess the footballer from their career path. Clubs are revealed one at a time — name the player who played for them all within five guesses.',
    keywords: ['football career path game', 'guess the footballer by clubs', 'career path football quiz', 'football transfer game'],
    h1: 'Career Path',
    tagline: 'Name the player who played for every club shown.',
    ogImage: '/og/career-path.png',
    about: 'Career Path is a football guessing game built around players’ club histories. You are shown one club from a mystery footballer’s career, and each wrong guess reveals the next club in their path. Work out who moved between all of them within five guesses.',
    howTo: [
      'A well-travelled footballer is chosen at random.',
      'The first club from their career is revealed.',
      'Guess who the player is — a wrong guess reveals the next club they played for.',
      'Identify the player who played for every club shown, within five guesses.',
    ],
    faq: [
      { q: 'How do I play Career Path?', a: 'You are shown one club from a mystery footballer’s career. Guess who it is; each wrong guess reveals another club they played for, up to five clubs.' },
      { q: 'How many guesses do I get?', a: 'You get five guesses, with a new club revealed after each wrong answer.' },
      { q: 'Are the career paths accurate?', a: 'Yes — the clubs come from each player’s real senior career, shown in the order they played for them.' },
    ],
    schema: 'VideoGame',
    priority: '0.9',
    changefreq: 'weekly',
  },
  {
    path: '/tenable',
    name: 'Football Tenable',
    title: 'Football Tenable — Name the Top 10 | Football Trivia Games',
    description: 'Play Football Tenable: a new football trivia question every day. Name as many of the top 10 answers as you can — three wrong guesses and it is game over.',
    keywords: ['football tenable', 'name the top 10 football', 'football top 10 quiz', 'football list trivia', 'football trivia daily'],
    h1: 'Football Tenable',
    tagline: 'Name as many of the top 10 as you can before three wrong guesses end it.',
    ogImage: '/og/tenable.png',
    about: 'Football Tenable is a daily list-based football quiz inspired by the TV format. Each question has ten correct answers — such as a competition’s all-time top scorers — and your job is to name as many as you can before three mistakes end the round.',
    howTo: [
      'Each day brings a new "name the top 10" football question.',
      'Type answers to fill in as many of the ten as you can.',
      'Every correct answer reveals its place on the list.',
      'Three wrong guesses ends the game — how many of the ten can you name?',
    ],
    faq: [
      { q: 'What is Football Tenable?', a: 'Football Tenable is a daily football trivia game where you try to name all ten answers to a top-10 question — such as a competition’s all-time top scorers — before making three mistakes.' },
      { q: 'How many lives do I have?', a: 'You can make up to three wrong guesses before the game ends.' },
      { q: 'Is there a new question each day?', a: 'Yes — a new top-10 question appears every day.' },
    ],
    schema: 'VideoGame',
    priority: '0.9',
    changefreq: 'daily',
  },
  {
    path: '/world-cup',
    name: 'Guess the World Cup',
    title: 'World Cup Quiz — Guess the World Cup | Football Trivia Games',
    description: 'Guess the World Cup from clues revealed one at a time — host, top scorer, finalists, winner. Name the tournament in five guesses, from 1930 to 2026.',
    keywords: ['world cup quiz', 'guess the world cup', 'world cup trivia', 'world cup 2026 quiz', 'football world cup game'],
    h1: 'Guess the World Cup',
    tagline: 'Identify the tournament from clues revealed one at a time.',
    ogImage: '/og/world-cup.png',
    about: 'Guess the World Cup is a football quiz about the FIFA World Cup. You are given clues about a mystery tournament — its hosts, Golden Boot winner, finalists and champions — one at a time, and you guess the year. It covers every World Cup from 1930 to the 2026 edition hosted by the United States, Canada and Mexico.',
    howTo: [
      'A FIFA World Cup tournament is chosen at random.',
      'The first clue — the host nation — is revealed.',
      'Pick the year you think it is; a wrong guess reveals the next clue (top scorer, runner-up, final score, then the winner).',
      'Name the tournament within five guesses.',
    ],
    faq: [
      { q: 'How do I play Guess the World Cup?', a: 'You are shown clues about a mystery FIFA World Cup — host, Golden Boot, runner-up, final score and winner — one at a time. Pick the year within five guesses.' },
      { q: 'Which tournaments are included?', a: 'Every men’s FIFA World Cup from 1930 to 2026, including the 2026 tournament hosted by the United States, Canada and Mexico.' },
      { q: 'Where does the data come from?', a: 'The tournament facts are sourced from Wikipedia’s record of FIFA World Cup finals and awards.' },
    ],
    schema: 'VideoGame',
    priority: '0.9',
    changefreq: 'weekly',
  },
  {
    path: '/connections',
    name: 'Football Connections',
    title: 'Football Connections — Daily Puzzle | Football Trivia Games',
    description: 'Football Connections: a daily puzzle of 16 footballers hiding four groups of four — clubs, nationalities and trophies. Find all four groups in four mistakes.',
    keywords: ['football connections', 'football connections game', 'daily football puzzle', 'football grouping game', 'connections football'],
    h1: 'Football Connections',
    tagline: 'Sort 16 players into four hidden groups of four.',
    ogImage: '/og/connections.png',
    about: 'Football Connections is a daily football puzzle inspired by the grouping game. Sixteen footballers hide four secret groups of four — by club, nationality or trophy. Work out which players belong together and solve all four groups before you make four mistakes.',
    howTo: [
      'Sixteen players are shown — they form four hidden groups of four.',
      'Select four players you think share a connection and submit.',
      'A correct group locks in and reveals its category; a wrong guess costs one of four lives.',
      'Solve all four groups before you run out of guesses.',
    ],
    faq: [
      { q: 'How do I play Football Connections?', a: 'Sixteen footballers hide four groups of four — by club, nationality or trophy. Pick four that belong together and submit; find all four groups within four mistakes.' },
      { q: 'Is there a new puzzle every day?', a: 'Yes — a fresh Football Connections puzzle is generated each day.' },
      { q: 'Does every puzzle have a single solution?', a: 'Yes. Each of the 16 players belongs to exactly one group, so there is always one correct way to solve it.' },
    ],
    schema: 'VideoGame',
    priority: '0.9',
    changefreq: 'daily',
  },
  {
    path: '/higher-or-lower',
    name: 'Higher or Lower',
    title: 'Football Higher or Lower | Football Trivia Games',
    description: 'Football Higher or Lower: pick which footballer scored more — Premier League, La Liga, Champions League or international goals — and build the longest streak.',
    keywords: ['football higher or lower', 'higher lower football', 'football streak game', 'football goals quiz', 'football guessing game'],
    h1: 'Football Higher or Lower',
    tagline: 'Pick which player scored more and build your streak.',
    ogImage: '/og/higher-or-lower.png',
    about: 'Football Higher or Lower is an endless streak game. Choose a stat — all-time Premier League, La Liga, Bundesliga, Champions League or international goals — then decide whether each new player scored more or fewer than the last. Every player is a genuine top scorer; keep choosing correctly to build your streak, and one wrong answer ends the run.',
    howTo: [
      'Choose a stat: top scorers of the Premier League, La Liga, Bundesliga, the Champions League, or for their country.',
      'Two players appear, with the first player’s goal tally revealed.',
      'Decide whether the second player scored more or fewer goals.',
      'A correct guess extends your streak; one wrong guess ends the run.',
    ],
    faq: [
      { q: 'How does Football Higher or Lower work?', a: 'You choose a goalscoring stat, then compare two footballers and pick which scored more. Correct guesses build a streak; one mistake ends it.' },
      { q: 'Which stats can I play?', a: 'All-time top scorers of the Premier League, La Liga, Bundesliga, the UEFA Champions League, and international goals for their country.' },
      { q: 'Does the game ever end?', a: 'Only when you guess wrong — new players keep coming, so the only limit is your streak.' },
    ],
    schema: 'VideoGame',
    priority: '0.8',
    changefreq: 'monthly',
  },
  {
    path: '/501',
    name: 'Football 501',
    title: 'Football 501 — Coming Soon | Football Trivia Games',
    description: 'Football 501, the darts-style football trivia game, is coming soon to Football Trivia Games.',
    keywords: ['football 501', 'football darts game'],
    h1: 'Football 501',
    tagline: 'The football darts trivia game — coming soon.',
    howTo: [],
    faq: [],
    schema: null,
    noindex: true, // disabled / coming soon — keep out of the index and sitemap
  },
]

export const routeByPath = (path) => ROUTES.find(r => r.path === path) || ROUTES[0]
export const indexableRoutes = () => ROUTES.filter(r => !r.noindex)

// ── Meta tags (consumed by client <Seo> and the prerender) ──────────────────
export function metaTagsFor(route) {
  const url = absolute(route.path)
  const ogImage = route.ogImage ? absolute(route.ogImage) : DEFAULT_OG_IMAGE
  const tags = [
    { name: 'description', content: route.description },
    { name: 'keywords', content: (route.keywords || []).join(', ') },
    { name: 'robots', content: route.noindex ? 'noindex, nofollow' : 'index, follow, max-image-preview:large' },
    { name: 'theme-color', content: '#0a0a0a' },
    { property: 'og:type', content: 'website' },
    { property: 'og:site_name', content: BRAND },
    { property: 'og:title', content: route.title },
    { property: 'og:description', content: route.description },
    { property: 'og:url', content: url },
    { property: 'og:image', content: ogImage },
    { property: 'og:image:width', content: '1200' },
    { property: 'og:image:height', content: '630' },
    { name: 'twitter:card', content: 'summary_large_image' },
    { name: 'twitter:title', content: route.title },
    { name: 'twitter:description', content: route.description },
    { name: 'twitter:image', content: ogImage },
    { name: 'twitter:site', content: TWITTER },
  ]
  return tags
}

// ── Structured data (JSON-LD) ───────────────────────────────────────────────
export function jsonLdFor(route) {
  const url = absolute(route.path)
  const blocks = []

  const organization = {
    '@type': 'Organization',
    '@id': `${SITE_URL}/#organization`,
    name: BRAND,
    url: SITE_URL + '/',
    logo: `${SITE_URL}/favicon.svg`,
  }

  if (route.path === '/') {
    blocks.push({
      '@context': 'https://schema.org',
      '@type': 'WebSite',
      '@id': `${SITE_URL}/#website`,
      url: SITE_URL + '/',
      name: BRAND,
      description: route.description,
      publisher: organization,
    })
    blocks.push({ '@context': 'https://schema.org', ...organization })
    blocks.push({
      '@context': 'https://schema.org',
      '@type': 'ItemList',
      name: 'Football trivia games',
      itemListElement: indexableRoutes().filter(r => r.path !== '/').map((r, i) => ({
        '@type': 'ListItem', position: i + 1, name: r.name, url: absolute(r.path),
      })),
    })
  } else if (route.schema === 'VideoGame') {
    blocks.push({
      '@context': 'https://schema.org',
      '@type': 'VideoGame',
      name: `${route.name} — ${BRAND}`,
      url,
      description: route.description,
      applicationCategory: 'GameApplication',
      genre: 'Trivia',
      gamePlatform: 'Web browser',
      operatingSystem: 'Any',
      inLanguage: 'en',
      isAccessibleForFree: true,
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      publisher: organization,
    })
    blocks.push({
      '@context': 'https://schema.org',
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Football Trivia Games', item: SITE_URL + '/' },
        { '@type': 'ListItem', position: 2, name: route.name, item: url },
      ],
    })
  }

  if (route.faq && route.faq.length) {
    blocks.push({
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: route.faq.map(f => ({
        '@type': 'Question', name: f.q,
        acceptedAnswer: { '@type': 'Answer', text: f.a },
      })),
    })
  }
  return blocks
}
