// ─────────────────────────────────────────────────────────────────────────
// CENTRAL SEO CONFIG — single source of truth for every route.
//
// Used by BOTH the client (<Seo> head manager, for SPA navigation) and the
// build-time prerender (scripts/prerender.mjs, which writes a unique static
// HTML file per route + sitemap.xml + robots.txt). Plain JS so Node and the
// browser can both import it. Change the domain in ONE place (SITE_URL).
// ─────────────────────────────────────────────────────────────────────────

import { ES } from './es.js'

export const SITE_URL = 'https://triviverse.com'
export const BRAND = 'Football Trivia Games'
export const TWITTER = '@footballtrivia'
export const LOCALES = ['en', 'es']
// 1200×630 social-share image (generated by scripts/og-images.mjs). Per-route
// images are set via route.ogImage; this is the fallback.
export const DEFAULT_OG_IMAGE = `${SITE_URL}/og/default.png`

export const absolute = (path) => (path === '/' ? SITE_URL + '/' : SITE_URL + path)
// Spanish is served under an /es prefix; English stays at the root.
export const localePrefix = (path, lang) => (lang === 'es' ? (path === '/' ? '/es' : `/es${path}`) : path)
export const absoluteFor = (path, lang) => absolute(localePrefix(path, lang))
// Merge Spanish overrides onto a route when lang === 'es'.
const localize = (route, lang) => (lang === 'es' && ES[route.path] ? { ...route, ...ES[route.path] } : route)
// hreflang alternates (both locales + x-default → English) for a route path.
export function alternatesFor(path) {
  return [
    { hreflang: 'en', href: absolute(path) },
    { hreflang: 'es', href: absoluteFor(path, 'es') },
    { hreflang: 'x-default', href: absolute(path) },
  ]
}

// One entry per route. Titles ≤ ~60 chars, descriptions ~150–160 chars,
// keyword-rich and unique (duplicate titles/descriptions are a ranking killer).
// `sections` adds longer-form, unique on-page copy (rendered visibly by
// SeoContent and into the prerendered static HTML) so each page is substantial
// rather than thin — which helps it get crawled AND indexed, not just discovered.
export const ROUTES = [
  {
    path: '/',
    name: 'Home',
    title: 'Football Trivia Games — Free Daily Football Quiz Games',
    description: 'Free daily football trivia games: Football Wordle, a footy Tic-Tac-Toe grid, name the top 10, and guess the player from their teammates. Play solo or 1v1.',
    keywords: ['football trivia games', 'football quiz', 'soccer trivia', 'daily football game', 'football guessing game'],
    h1: 'Football Trivia Games',
    tagline: 'A growing collection of free daily football trivia games. No sign-up, just play.',
    about: 'Football Trivia Games brings together the best free daily football quiz games in one place. Test your knowledge with Football Wordle, fill a Football Tic-Tac-Toe grid, race against the clock in Football Tenable, or guess the mystery player from their teammates — all playable instantly in your browser on mobile or desktop.',
    howTo: [],
    sections: [
      {
        h2: 'Free football games you can play every day',
        body: [
          'Every game here is completely free, runs instantly in your browser, and needs no account, app or download. Pick a game, play a round in a couple of minutes, then come back tomorrow for a fresh challenge.',
          'Most games have a Daily mode — the same puzzle for everyone, with a win streak to protect — plus an Unlimited mode for endless practice that never touches your stats.',
        ],
      },
      {
        h2: 'A game for every kind of football fan',
        body: [
          'Word-game lovers can tackle Football Wordle; quiz buffs will enjoy Football Tenable and Football Connections; and anyone who knows their transfers will fly through Teammates and Career Path. Test your memory with Name the Winning Squad, or chase a streak in Higher or Lower. Whether you follow the Premier League, La Liga, the Champions League or the World Cup, there is a daily football game here for you.',
        ],
      },
    ],
    faq: [
      { q: 'What is Football Trivia Games?', a: 'Football Trivia Games is a free collection of daily football quiz games — including Football Wordle, Football Tic-Tac-Toe, Football Tenable and Guess the Player — playable in your browser with no sign-up.' },
      { q: 'Are the games free to play?', a: 'Yes. Every game is completely free, runs in your browser, and needs no account or download.' },
      { q: 'Do new puzzles appear every day?', a: 'Yes. The daily games refresh at local midnight, and the guessing and 1v1 modes can be replayed as often as you like.' },
      { q: 'Can I play more than once a day?', a: 'Yes — most games have an Unlimited mode for endless practice alongside the once-a-day Daily challenge, and the 1v1 and guessing modes can be replayed any time.' },
      { q: 'Can I play on my phone?', a: 'Yes. Every game works in any mobile or desktop browser, with no app to install.' },
    ],
    schema: 'WebSite',
    priority: '1.0',
    changefreq: 'daily',
  },
  {
    path: '/wordle',
    name: 'Football Wordle',
    title: 'Football Wordle — Guess the Footballer | Football Trivia Games',
    description: "Play Football Wordle: guess the mystery footballer's surname in six tries. A new player every day — green is the right spot, yellow the right letter, wrong spot.",
    keywords: ['football wordle', 'footdle', 'soccer wordle', 'guess the footballer', 'footballer wordle', 'football word game'],
    h1: 'Football Wordle',
    tagline: "Guess the mystery footballer's surname in six tries.",
    ogImage: '/og/wordle.png',
    about: 'Football Wordle is a daily football word game in the style of Wordle. Each day a famous footballer is chosen and you have six guesses to work out their surname, using green and yellow letter clues to narrow it down. It is a quick, addictive test for any football fan.',
    howTo: [
      'A new famous footballer is chosen every day.',
      'Type a real surname and submit your guess.',
      'Green means the letter is in the right spot; yellow means right letter, wrong spot; grey means it is not in the surname.',
      'Solve the surname within six guesses to win.',
    ],
    sections: [
      {
        h2: 'Tips for Football Wordle',
        body: [
          'Open with a surname packed with common letters so you light up as many greens and yellows as possible — names rich in vowels and letters like R, S, T and N make a strong first guess.',
          'Accents are ignored, so you never have to spell a name with its exact diacritics — just get the letters right and let the colours guide you.',
        ],
      },
      {
        h2: 'How it differs from the original Wordle',
        body: [
          'Instead of a fixed five-letter word, you are guessing a real footballer’s surname, which can be longer or shorter than five letters. Every answer is a genuinely famous player, so Football Wordle rewards football knowledge as much as word skill.',
        ],
      },
    ],
    faq: [
      { q: 'What is Football Wordle?', a: "Football Wordle is a daily word game where you guess a famous footballer's surname in six tries, using green and yellow colour clues just like Wordle." },
      { q: 'How many guesses do I get?', a: 'You get six guesses to find the footballer’s surname.' },
      { q: 'Does the footballer change every day?', a: 'Yes — a new footballer is selected each day and refreshes at local midnight.' },
      { q: 'Is Football Wordle the same as Footdle?', a: "Yes — Football Wordle is a footballer Wordle, sometimes searched as Footdle or soccer Wordle: guess the mystery footballer's surname in six tries using green and yellow letter clues." },
      { q: 'Is there a Daily and an Unlimited mode?', a: 'Yes. Daily gives everyone the same footballer each day and tracks your win streak; Unlimited serves random players for endless practice without affecting your stats.' },
    ],
    schema: 'VideoGame',
    priority: '0.9',
    changefreq: 'daily',
  },
  {
    path: '/tictactoe',
    name: 'Football Tic-Tac-Toe',
    title: 'Football Tic-Tac-Toe — Daily Grid & 1v1 | Football Trivia Games',
    description: 'Play Football Tic-Tac-Toe: a 3x3 grid where every row and column is a football category. Name a player who fits both to claim a square. Daily solo grid or local 1v1.',
    keywords: ['football tic tac toe', 'tiki taka toe', 'tiki-taka-toe', 'footy grid', 'football grid', 'immaculate grid football', 'immaculate footy', 'footy tic tac toe', 'soccer tic tac toe'],
    h1: 'Football Tic-Tac-Toe',
    tagline: 'Two football categories meet in every square — name a player who fits both.',
    ogImage: '/og/tictactoe.png',
    about: 'Football Tic-Tac-Toe, also known as a footy grid, challenges your knowledge of clubs, leagues, nationalities and trophies. Claim a square by naming a footballer who matches both its row and column category — then play the daily grid solo or go head-to-head with a friend in local 1v1 mode.',
    howTo: [
      'Every row and column is a football category — a club, league, nationality or trophy.',
      'Pick a square and name a player who satisfies BOTH its row and column category.',
      'No player can be used twice on the same grid.',
      'In the daily mode, fill all nine squares before your lives run out. In 1v1, take turns and get three in a row to win.',
    ],
    sections: [
      {
        h2: 'Tips & strategy',
        body: [
          'Look for versatile players who satisfy several categories at once — a well-travelled international who has won major trophies can unlock multiple squares. Start with the square you find hardest, because once a player is used they cannot be reused anywhere else on the grid.',
        ],
      },
      {
        h2: 'The categories you will see',
        body: [
          'Rows and columns are drawn from clubs, leagues, nationalities and trophies — for example “Played for Real Madrid”, “Premier League”, “Brazil international” or “Won the Ballon d’Or”. Every daily grid is checked to be solvable with famous players, so there is always a satisfying answer for each square.',
        ],
      },
    ],
    faq: [
      { q: 'How does Football Tic-Tac-Toe work?', a: 'Each row and column of the 3x3 grid is a football category. To claim a square you name a player who fits both the row and the column — for example a player who played for a given club AND won a given trophy.' },
      { q: 'Can I play Football Tic-Tac-Toe with a friend?', a: 'Yes. The 1v1 mode lets two players share one device, taking turns to claim squares. The first to three in a row wins, and you can even build your own grid by choosing the categories.' },
      { q: 'Does the daily grid change every day?', a: 'Yes — the daily challenge generates a fresh, solvable grid each day.' },
      { q: 'Is this the same as Tiki-Taka-Toe or a footy grid?', a: 'Yes — Football Tic-Tac-Toe is the same idea as Tiki-Taka-Toe and other footy grid games, and a football take on the Immaculate Grid: name a player who fits both a row and a column category on a 3x3 grid.' },
      { q: 'Is there a Daily and an Unlimited mode?', a: 'Yes. Daily is one shared grid a day that tracks your win streak; Unlimited generates random grids for endless practice without affecting your stats.' },
    ],
    schema: 'VideoGame',
    priority: '0.9',
    changefreq: 'daily',
  },
  {
    path: '/teammates',
    name: 'Teammates',
    title: 'Teammates — Guess the Footballer | Football Trivia Games',
    description: 'Guess the mystery footballer from their real teammates, revealed one at a time. Work out who it is in five guesses in this addictive football guessing game.',
    keywords: ['guess the footballer', 'who are ya', 'who are ya football', 'guess the football player', 'football guessing game', 'name the footballer', 'teammates football game'],
    h1: 'Teammates',
    tagline: 'Identify the mystery footballer from the players they actually played with.',
    ogImage: '/og/teammates.png',
    about: 'Guess the Player is a football guessing game where you identify a mystery footballer from the real players they lined up alongside. A new teammate is revealed after every wrong guess, so the more football you know, the faster you will crack it.',
    howTo: [
      'A well-known footballer is chosen at random.',
      'One of their real former teammates is revealed.',
      'Guess who the mystery player is. A wrong guess reveals another teammate.',
      'Work it out within five guesses to win.',
    ],
    sections: [
      {
        h2: 'Tips for guessing the player',
        body: [
          'Use the first teammate to pin down an era and a club, then let each new clue narrow the nationality and position. Spread your early guesses across different players who fit the clues rather than fixating on a single name.',
        ],
      },
      {
        h2: 'Where the clues come from',
        body: [
          'Each revealed teammate genuinely played alongside the mystery footballer at a club or national team during overlapping seasons, and the clues are deliberately spread across the different teams of their career — so a well-travelled player’s clues cover their whole journey.',
        ],
      },
    ],
    faq: [
      { q: 'How do I play Guess the Player?', a: 'You are shown one real teammate of a mystery footballer. Guess who the mystery player is; each wrong guess reveals another teammate, up to five clues.' },
      { q: 'How many guesses do I get?', a: 'You get five guesses, with a new teammate revealed after each wrong answer.' },
      { q: 'Are the teammates accurate?', a: 'Yes — teammates are players who genuinely shared a club or national team during overlapping years.' },
      { q: 'Is this a "Who Are Ya?" football guessing game?', a: 'Yes — it is a guess-the-footballer game in the "Who Are Ya?" style: work out the mystery player from the real teammates they lined up alongside.' },
      { q: 'Is there a Daily and an Unlimited mode?', a: 'Yes. Daily sets one mystery player a day and tracks your win streak; Unlimited gives you random players to practise with, without affecting your stats.' },
    ],
    schema: 'VideoGame',
    priority: '0.9',
    changefreq: 'weekly',
  },
  {
    path: '/career-path',
    name: 'Career Path',
    title: 'Career Path — Guess the Footballer | Football Trivia Games',
    description: 'Guess the footballer from their career path. Clubs are revealed one at a time — name the player who played for them all within five guesses.',
    keywords: ['football career path game', 'guess the footballer by clubs', 'career path football quiz', 'football transfer game'],
    h1: 'Career Path',
    tagline: 'Name the player who played for every club shown.',
    ogImage: '/og/career-path.png',
    about: 'Career Path is a football guessing game built around players’ club histories. You are shown one club from a mystery footballer’s career, and each wrong guess reveals the next club in their path. Work out who moved between all of them within five guesses.',
    howTo: [
      'A well-travelled footballer is chosen at random.',
      'The first club from their career is revealed.',
      'Guess who the player is — a wrong guess reveals the next club they played for.',
      'Identify the player who played for every club shown, within five guesses.',
    ],
    sections: [
      {
        h2: 'Tips for cracking the career path',
        body: [
          'The order and years of the clubs are your biggest clues — a distinctive transfer between two clubs in a particular season often gives the player away. Counter-intuitively, journeyman players with many clubs can be easier to spot than one-club legends.',
        ],
      },
      {
        h2: 'Career Path vs Teammates',
        body: [
          'Both games ask you to name a mystery footballer, but Career Path reveals the clubs they played for in order, while Teammates reveals the players they lined up alongside. Try both to see which style suits your knowledge best.',
        ],
      },
    ],
    faq: [
      { q: 'How do I play Career Path?', a: 'You are shown one club from a mystery footballer’s career. Guess who it is; each wrong guess reveals another club they played for, up to five clubs.' },
      { q: 'How many guesses do I get?', a: 'You get five guesses, with a new club revealed after each wrong answer.' },
      { q: 'Are the career paths accurate?', a: 'Yes — the clubs come from each player’s real senior career, shown in the order they played for them.' },
      { q: 'Is there a Daily and an Unlimited mode?', a: 'Yes. Daily sets one career path a day and tracks your win streak; Unlimited gives you random players to practise with, without affecting your stats.' },
    ],
    schema: 'VideoGame',
    priority: '0.9',
    changefreq: 'weekly',
  },
  {
    path: '/tenable',
    name: 'Football Tenable',
    title: 'Football Tenable — Name the Top 10 | Football Trivia Games',
    description: 'Play Football Tenable — the daily footy top-10 quiz (a.k.a. Tenaball). Name as many of the 10 answers as you can; three wrong guesses and it is game over.',
    keywords: ['football tenable', 'footy tenable', 'tenable football', 'tenaball', 'footy tenaball', 'football tenaball', 'name the top 10 football', 'football top 10 quiz'],
    h1: 'Football Tenable',
    tagline: 'Name as many of the top 10 as you can before three wrong guesses end it.',
    ogImage: '/og/tenable.png',
    about: 'Football Tenable is a daily list-based football quiz inspired by the TV format. Each question has ten correct answers — such as a competition’s all-time top scorers — and your job is to name as many as you can before three mistakes end the round.',
    howTo: [
      'Each day brings a new "name the top 10" football question.',
      'Type answers to fill in as many of the ten as you can.',
      'Every correct answer reveals its place on the list.',
      'Three wrong guesses ends the game — how many of the ten can you name?',
    ],
    sections: [
      {
        h2: 'Tips for Football Tenable',
        body: [
          'Brain-dump the obvious answers first to bank easy points, then work through the list by era, nationality or club to flush out the names you are missing. With only three lives, it pays to be sure before you commit to a guess.',
        ],
      },
      {
        h2: 'About the top-10 format',
        body: [
          'Inspired by the TV quiz, every Football Tenable question has exactly ten correct answers — such as a competition’s all-time top scorers, a club’s record appearance-makers, or the teams with the most titles — and your job is to name as many as you can.',
        ],
      },
    ],
    faq: [
      { q: 'What is Football Tenable?', a: 'Football Tenable is a daily football trivia game where you try to name all ten answers to a top-10 question — such as a competition’s all-time top scorers — before making three mistakes.' },
      { q: 'Is this the football version of Tenable?', a: "Yes — Football Tenable (also searched as 'Tenaball', 'footy tenaball' or 'footy Tenable') is a daily top-10 football quiz inspired by the ITV game show Tenable. Name as many of the top 10 as you can before three wrong guesses." },
      { q: 'How many lives do I have?', a: 'You can make up to three wrong guesses before the game ends.' },
      { q: 'Is there a new question each day?', a: 'Yes — a new top-10 question appears every day.' },
      { q: 'Is there a Daily and an Unlimited mode?', a: 'Yes. Daily is one shared question a day that tracks your win streak; Unlimited serves random questions for endless practice without affecting your stats.' },
    ],
    schema: 'VideoGame',
    priority: '0.9',
    changefreq: 'daily',
  },
  {
    path: '/world-cup',
    name: 'World Cup Squads',
    title: 'Name the World Cup Winning Squad | Football Trivia Games',
    description: 'Name the Winning Squad: pick a World Cup-winning team — Brazil 2002, France 98, Argentina 2022 — and recall as many of the squad as you can.',
    keywords: ['world cup squads', 'name the world cup squad', 'world cup winning teams quiz', 'football squad quiz', 'world cup 2022 squad'],
    h1: 'Name the Winning Squad',
    tagline: 'How many of a World Cup-winning squad can you name?',
    ogImage: '/og/world-cup.png',
    about: 'Name the Winning Squad is a football memory game about the FIFA World Cup. Pick one of the great World Cup-winning teams — from England 1966 to Argentina 2022 — and type as many of its 22-to-26-man squad as you can recall, including the reserves. How well do you really know the legendary teams?',
    howTo: [
      'Choose a World Cup-winning team (e.g. Brazil 2002, France 1998, Argentina 2022).',
      'Type the names of players who were in that winning squad.',
      'Each correct name fills in its place; the counter tracks how many of the full squad you have.',
      'Recall as many as you can — then reveal the rest to see who you missed.',
    ],
    sections: [
      {
        h2: 'Tips for naming the squad',
        body: [
          'Work through the team position by position — start with the famous starting XI, then dig into the substitutes and squad players who are easy to forget. Running through the matches you remember from the tournament often jogs loose the deeper cuts.',
        ],
      },
      {
        h2: 'The winning squads',
        body: [
          'Play any World Cup-winning squad from England 1966 right through to Argentina 2022, including iconic teams like Brazil 1970, Italy 1982, France 1998, Italy 2006 and Spain 2010. Each squad is sourced from the official tournament record, reserves and all.',
        ],
      },
    ],
    faq: [
      { q: 'How do I play Name the Winning Squad?', a: 'Pick a World Cup-winning team and type the players from its squad. Every correct name is revealed and counted; try to name the whole 22-to-26-man squad.' },
      { q: 'Which teams can I play?', a: 'Every World Cup-winning squad from England 1966 through to Argentina 2022.' },
      { q: 'Where do the squads come from?', a: 'The squads are sourced from Wikipedia’s official record of FIFA World Cup winning players.' },
      { q: 'Is there a Daily and an Unlimited mode?', a: 'Yes. Daily gives everyone the same “squad of the day” and tracks your best score and day streak; Unlimited lets you pick any winning squad to practise, without affecting your stats.' },
    ],
    schema: 'VideoGame',
    priority: '0.9',
    changefreq: 'weekly',
  },
  {
    path: '/connections',
    name: 'Football Connections',
    title: 'Football Connections — Daily Puzzle | Football Trivia Games',
    description: 'Football Connections: a daily puzzle of 16 footballers hiding four groups of four — clubs, nationalities and trophies. Find all four groups in four mistakes.',
    keywords: ['football connections', 'football connections game', 'daily football puzzle', 'football grouping game', 'connections football'],
    h1: 'Football Connections',
    tagline: 'Sort 16 players into four hidden groups of four.',
    ogImage: '/og/connections.png',
    about: 'Football Connections is a daily football puzzle inspired by the grouping game. Sixteen footballers hide four secret groups of four — by club, nationality or trophy. Work out which players belong together and solve all four groups before you make four mistakes.',
    howTo: [
      'Sixteen players are shown — they form four hidden groups of four.',
      'Select four players you think share a connection and submit.',
      'A correct group locks in and reveals its category; a wrong guess costs one of four lives.',
      'Solve all four groups before you run out of guesses.',
    ],
    sections: [
      {
        h2: 'Tips for Football Connections',
        body: [
          'Start with the group you are most certain about, but watch for decoys — a player who looks like an obvious fit for one group may actually be there to complete another. When you are stuck, look for the four players that share the least obvious link.',
          'Every puzzle has exactly one solution: each of the 16 players belongs to a single group, so there are no genuine overlaps designed to trick you — only your own assumptions.',
        ],
      },
    ],
    faq: [
      { q: 'How do I play Football Connections?', a: 'Sixteen footballers hide four groups of four — by club, nationality or trophy. Pick four that belong together and submit; find all four groups within four mistakes.' },
      { q: 'Is there a new puzzle every day?', a: 'Yes — a fresh Football Connections puzzle is generated each day.' },
      { q: 'Does every puzzle have a single solution?', a: 'Yes. Each of the 16 players belongs to exactly one group, so there is always one correct way to solve it.' },
      { q: 'Is there a Daily and an Unlimited mode?', a: 'Yes. Daily is one shared puzzle a day that tracks your win streak; Unlimited generates random puzzles for endless practice without affecting your stats.' },
    ],
    schema: 'VideoGame',
    priority: '0.9',
    changefreq: 'daily',
  },
  {
    path: '/higher-or-lower',
    name: 'Higher or Lower',
    title: 'Football Higher or Lower | Football Trivia Games',
    description: 'Football Higher or Lower: pick which footballer scored more — Premier League, La Liga, Champions League or international goals — and build the longest streak.',
    keywords: ['football higher or lower', 'higher lower football', 'football streak game', 'football goals quiz', 'football guessing game'],
    h1: 'Football Higher or Lower',
    tagline: 'Pick which player scored more and build your streak.',
    ogImage: '/og/higher-or-lower.png',
    about: 'Football Higher or Lower is an endless streak game. Choose a stat — all-time Premier League, La Liga, Bundesliga, Champions League or international goals — then decide whether each new player scored more or fewer than the last. Every player is a genuine top scorer; keep choosing correctly to build your streak, and one wrong answer ends the run.',
    howTo: [
      'Choose a stat: top scorers of the Premier League, La Liga, Bundesliga, the Champions League, or for their country.',
      'Two players appear, with the first player’s goal tally revealed.',
      'Decide whether the second player scored more or fewer goals.',
      'A correct guess extends your streak; one wrong guess ends the run.',
    ],
    sections: [
      {
        h2: 'Tips for Higher or Lower',
        body: [
          'Get to know the record scorers at the top of each list — once you have a feel for who sits near the all-time peaks, comparisons become much easier. Remember that a tie counts as correct either way, so the closest calls are not always a trap.',
        ],
      },
      {
        h2: 'The stats you compare',
        body: [
          'Choose from all-time top scorers of the Premier League, La Liga, Bundesliga and the UEFA Champions League, or international goals for a country. Every player shown is a real record-holder, so there are no obscure names — just how well you know the goalscoring charts.',
        ],
      },
    ],
    faq: [
      { q: 'How does Football Higher or Lower work?', a: 'You choose a goalscoring stat, then compare two footballers and pick which scored more. Correct guesses build a streak; one mistake ends it.' },
      { q: 'Which stats can I play?', a: 'All-time top scorers of the Premier League, La Liga, Bundesliga, the UEFA Champions League, and international goals for their country.' },
      { q: 'Does the game ever end?', a: 'Only when you guess wrong — new players keep coming, so the only limit is your streak.' },
      { q: 'Is there a Daily and an Unlimited mode?', a: 'Yes. Daily gives everyone the same chain of players each day and tracks your best score and day streak; Unlimited lets you pick a stat and play endless random rounds without affecting your stats.' },
    ],
    schema: 'VideoGame',
    priority: '0.8',
    changefreq: 'monthly',
  },
  {
    path: '/501',
    name: 'Football 501',
    title: 'Football 501 — Football Darts Game | Football Trivia Games',
    description: 'Football 501 is the darts-style football stats game — count down from 501 by naming footballers by appearances or goals, all-time across Europe’s top leagues.',
    keywords: ['football 501', 'football darts game', 'footy darts', 'football darts trivia', 'football stats game', 'name the footballer game', 'premier league darts game', 'all-time top scorers game', 'guess the footballer by stats', 'football checkout game'],
    h1: 'Football 501',
    tagline: 'Count down from 501 by naming footballers — land the perfect checkout.',
    ogImage: '/og/501.png',
    about: 'Football 501 is a darts-inspired football stats game. You start on 501 and count down by naming footballers — each player’s real career appearances or goals are deducted from your score. Like darts, you check out by landing between 0 and −10, so controlling your countdown is the real skill. It spans the all-time records of the Premier League, La Liga, Serie A, Bundesliga, Ligue 1 and the Champions League — from Alan Shearer and Gerd Müller to Lionel Messi.',
    howTo: [
      'Each day brings a new challenge — a stat (appearances or goals), a competition, and a filter like club, nationality or position.',
      'Name footballers who fit; their real career total is deducted from 501.',
      'Keep your countdown under control — a player worth over 180 busts your visit.',
      'Check out by landing between 0 and −10. Drop below −10 and you bust.',
    ],
    sections: [
      {
        h2: 'Every competition, all-time',
        body: [
          'Football 501 covers six competitions back to their founding: the Premier League (Alan Shearer’s 260 goals), La Liga (Lionel Messi’s 474), Serie A (Silvio Piola), the Bundesliga (Gerd Müller’s 365), Ligue 1 and the Champions League. Questions can be top scorers, most appearances, or clever combinations, filtered by club, nationality or position — a fresh one every day.',
        ],
      },
      {
        h2: 'Tips for Football 501',
        body: [
          'The skill is in the countdown, not the big names. Deduct the heavy hitters early to bring 501 down quickly, then save the lower-value players for your checkout so you can land cleanly between 0 and −10 without busting. Watch the live boxes for the biggest safe answer and how many checkouts remain.',
        ],
      },
      {
        h2: 'Play solo or with friends',
        body: [
          'Play the daily on your own, or start a local multiplayer game for 2–5 players who take turns on one device — closest to a clean checkout wins. Build-your-own lets you pick the exact competition, stat and filters for the question.',
        ],
      },
    ],
    faq: [
      { q: 'What is Football 501?', a: 'Football 501 is a darts-style football stats game. You count down from 501 by naming footballers, and each player’s real career appearances or goals in the chosen competition are deducted from your score — land between 0 and −10 to check out.' },
      { q: 'Which competitions can I play?', a: 'Six, all-time back to their founding: the Premier League, La Liga, Serie A, Bundesliga, Ligue 1 and the Champions League. The daily rotates across all of them.' },
      { q: 'How do you win?', a: 'You check out by landing your score between 0 and −10, exactly like a darts finish. Going below −10 busts, and a single player worth more than 180 busts the visit — so controlling your countdown is the key skill.' },
      { q: 'Is there a new challenge each day?', a: 'Yes — a new daily challenge every day, drawn from any competition, with a different stat and filter each time.' },
      { q: 'Can I play with friends?', a: 'Yes — local multiplayer for 2–5 players on one device, plus a build-your-own mode where you set the competition, stat and filters yourself.' },
      { q: 'Where do the stats come from?', a: 'Every player’s appearances and goals are sourced from Transfermarkt’s competition records, all the way back to each league’s founding season.' },
    ],
    schema: 'VideoGame',
    priority: '0.9',
    changefreq: 'daily',
  },
]

export const routeByPath = (path, lang = 'en') => localize(ROUTES.find(r => r.path === path) || ROUTES[0], lang)
export const indexableRoutes = () => ROUTES.filter(r => !r.noindex)

// ── Meta tags (consumed by client <Seo> and the prerender) ──────────────────
// `route` should already be localized (via routeByPath(path, lang)); `lang`
// only drives the URL prefix and og:locale.
export function metaTagsFor(route, lang = 'en') {
  const url = absoluteFor(route.path, lang)
  const ogImage = route.ogImage ? absolute(route.ogImage) : DEFAULT_OG_IMAGE
  const tags = [
    { name: 'description', content: route.description },
    { name: 'keywords', content: (route.keywords || []).join(', ') },
    { name: 'robots', content: route.noindex ? 'noindex, nofollow' : 'index, follow, max-image-preview:large' },
    { name: 'theme-color', content: '#080c08' }, // pitch — must match the body canvas (design-tokens.md §1.1)
    { property: 'og:type', content: 'website' },
    { property: 'og:site_name', content: BRAND },
    { property: 'og:locale', content: lang === 'es' ? 'es_ES' : 'en_GB' },
    { property: 'og:locale:alternate', content: lang === 'es' ? 'en_GB' : 'es_ES' },
    { property: 'og:title', content: route.title },
    { property: 'og:description', content: route.description },
    { property: 'og:url', content: url },
    { property: 'og:image', content: ogImage },
    { property: 'og:image:width', content: '1200' },
    { property: 'og:image:height', content: '630' },
    { name: 'twitter:card', content: 'summary_large_image' },
    { name: 'twitter:title', content: route.title },
    { name: 'twitter:description', content: route.description },
    { name: 'twitter:image', content: ogImage },
    { name: 'twitter:site', content: TWITTER },
  ]
  return tags
}

// ── Structured data (JSON-LD) ───────────────────────────────────────────────
export function jsonLdFor(route, lang = 'en') {
  const url = absoluteFor(route.path, lang)
  const blocks = []

  const organization = {
    '@type': 'Organization',
    '@id': `${SITE_URL}/#organization`,
    name: BRAND,
    url: SITE_URL + '/',
    logo: `${SITE_URL}/favicon.svg`,
  }

  if (route.path === '/') {
    blocks.push({
      '@context': 'https://schema.org',
      '@type': 'WebSite',
      '@id': `${SITE_URL}/#website`,
      url: SITE_URL + '/',
      name: BRAND,
      description: route.description,
      publisher: organization,
    })
    blocks.push({ '@context': 'https://schema.org', ...organization })
    blocks.push({
      '@context': 'https://schema.org',
      '@type': 'ItemList',
      name: 'Football trivia games',
      itemListElement: indexableRoutes().filter(r => r.path !== '/').map((r, i) => ({
        '@type': 'ListItem', position: i + 1, name: r.name, url: absolute(r.path),
      })),
    })
  } else if (route.schema === 'VideoGame') {
    blocks.push({
      '@context': 'https://schema.org',
      '@type': 'VideoGame',
      name: `${route.name} — ${BRAND}`,
      url,
      description: route.description,
      applicationCategory: 'GameApplication',
      genre: 'Trivia',
      gamePlatform: 'Web browser',
      operatingSystem: 'Any',
      inLanguage: 'en',
      isAccessibleForFree: true,
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      publisher: organization,
    })
    blocks.push({
      '@context': 'https://schema.org',
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Football Trivia Games', item: SITE_URL + '/' },
        { '@type': 'ListItem', position: 2, name: route.name, item: url },
      ],
    })
  }

  if (route.faq && route.faq.length) {
    blocks.push({
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: route.faq.map(f => ({
        '@type': 'Question', name: f.q,
        acceptedAnswer: { '@type': 'Answer', text: f.a },
      })),
    })
  }
  return blocks
}
